### ISSUE TITLE
proposedRides don't persist accross login

### ISSUE THREAD

**Issue by toastedcornflakes** [Robin-gielen/Covoituride-2nd#1]
When I propose a ride, log out then log back in, the right isn't in `proposedRides` anymore. It is still accessible by search.

**Comment by Robin-gielen** [comment]
Didn't notice that, tried it again and it seems to work.

**Comment by toastedcornflakes** [comment]
I just tested again and can't reproduce, should have been fixed between b01b5325523f7429cd1233eb9e1eec788dee96d6 and now 👍
